name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          include:
            - os: linux
              arch: amd64
            - os: linux
              arch: arm64
      steps:
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
          go-version: 1.15
         
       - name: Build
         run: go build -v ./...
         
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
       
       - name: Docker Login
         uses: docker/login-action@v1
         with:  
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
       
       - name: Build and push
         id  : docker_build
         uses: docker/build-push-action@v2
         with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-ci-cd:multiples
