name: multiple platforms and caching
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore-keys: |
         ${{ runner.os }}-go- 
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1
      with:  
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Cache docker layers
      uses: actions/cache@v2
      id: cache 
      with:  
        path: /tmp/.buildx-cache
        key: ${{runner.os}}-buildx-${{github.sha}}
        restore-keys: |
         ${{ runner.os }}-buildx-

    - name: Build and Push Docker Iamge
      id  : docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-ci-cd:cachedv1